config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'dashboard#index'
  
  get 'dashboard', to: 'dashboard#index'
  get 'leaderboard', to: 'leaderboard#index'

  resources :teachers, only: %w[index create]
  resources :subscriptions, only: %w[index show create]
  resources :votes, only: %w[create]

  resources :courses, only: %w[index show] do
    resources :subscriptions, only: %w[index new]
    resources :teachers, only: %w[index new]
  end

  get ':votable_type/:votable_id/votes', to: 'votes#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses

  validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category

  has_many :subscriptions
  has_many :teachers, through: :subscriptions
  has_many :votes, as: :votable

  validates :title, :tags, :category_id, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :teacher
  belongs_to :course

  has_many :votes, as: :votable

  validates :teacher_id, :course_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :subscriptions
  has_many :courses, through: :subscriptions

  validates :email, :first_name, :last_name, :specialism, presence: true
  validates :email, uniqueness: { case_sensitive: false }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :voted_by, foreign_key: :voted_by_id, class_name: 'Teacher'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_category
  before_action :set_categories
  before_action :set_course, only: :show

  def index
    @pagy, @courses = pagy(@category.nil? ? Course.all : @category.courses)
  end

  def show
  end

  private

  def set_category
    @category = Category.find_by(id: params[:category_id])
  end

  def set_categories
    @categories = Category.all
  end

  def set_course
    @course = Course.find_by(id: params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @courses_count = Course.count
    @teachers_count = Teacher.count
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_course
  before_action :set_categories
  before_action :set_subscription, only: :show

  def index
    @pagy, @subscriptions = pagy(@course.nil? ? Subscription.all : @course.subscriptions)
  end

  def show
  end

  def new
    @subscription = @course.subscriptions.new
  end

  def create
    create_service = Subscriptions::CreateService.new(subscription_params)

    if create_service.call
      redirect_to course_path(create_service.subscription.course), notice: 'Subscription was successfully created.'
    else
      @subscription = create_service.subscription
      render :new
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:course_id, :teacher_id, :teacher_email, :teacher_first_name, :teacher_last_name, :teacher_specialism)
  end

  def set_course
    @course = Course.find_by(id: params[:course_id])
  end

  def set_subscription
    @subscription = Subscription.find_by(id: params[:id])
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_course, only: :index
  
  def index
    search_query = Teachers::SearchQuery.new(search_params)
    search_query.call
    @pagy, @teachers = pagy(search_query.teachers)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    create_service = Teachers::CreateService.new(teacher_params)

    if create_service.call
      redirect_to create_service.teacher, notice: 'Teacher was successfully created.'
    else
      render :new, teacher: create_service.teacher
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:email, :first_name, :last_name)
  end

  def search_params
    params.permit(:email, :course_id)
  end

  def set_course
    @course = Course.find_by(id: params[:course_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_votable, only: :index

  def index
    @pagy, @votes = pagy(@votable.votes)
  end

  def create
    create_service = Votes::CreateService.new(vote_params)

    if create_service.call
      redirect_to request.referrer, notice: 'Vote was successfully created.'
    else
      @vote = create_service.vote
      render :new
    end
  end

  private

  def vote_params
    params.permit(:votable_id, :votable_type, :email)
  end

  def set_votable
    @votable = Object.const_get(params[:votable_type].to_s.capitalize).find_by(id: params[:votable_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
  def teacher_full_name(teacher)
    return unless teacher.class == Teacher

    "#{teacher.first_name} #{teacher.last_name}"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/courses/_categories.html.erb
<div class='navbar-vertical'>
  <ul>
    <li class='item-li'>
      <%= link_to 'All', courses_path, class: "#{'selected' unless selected_category}" %>
    </li>
    <% @categories.each do |category| %>
      <li class='item-li'>
        <%= link_to category.name, courses_path(category_id: category.id), class: "#{'selected' if category.id == selected_category&.id}" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/courses/_course.html.erb
<div class="column">
  <div class="card">
    <img src="<%= course.image_src %>" width="100%">
    <h3><%= course.title %></h3>
    <p>
      <% course.tags.each do |tag| %>
        <span class='tag'><%= tag %></span>
      <% end %>
    </p>
    <p><%= course.description %></p>
    <%= link_to 'See course', course_path(course), class: 'see-button' %>
    <%= link_to 'Subscribe', new_course_subscription_path(course_id: course.id), class: 'inscription-button' %>
    <br><br>
    <%= link_to "#{course.teachers.count} Teachers", course_teachers_path(course_id: course.id), class: '' %>
    <br>
    <%= link_to "#{course.votes.count} Votes", "/course/#{course.id}/votes", class: '' %>
  </div>
</div>

app/views/courses/index.html.erb
<section class="container">
  <div class="left-container">
    <%= render 'categories', selected_category: @category %>
  </div>
  <div class="right-container">
    <div class="row">
      <div class="column"><h2><%= @category.nil? ? 'All Courses' : "Courses - #{@category.name}" %></h2></div>
    </div>
    <div class="row">
      <% @courses.each do |course| %>
        <%= render partial: 'course', locals: { course: course } %>
      <% end %>
    </div>
    <div class="pagination-row">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</secion>

app/views/courses/show.html.erb
<section class="container">
  <div class="right-container">
    <div class="row">
      <div class='column'>
        <div class="card">
          <img src="<%= @course.image_src %>" width="300px">
          <h3><%= @course.title %></h3>
          <p>
            <% @course.tags.each do |tag| %>
              <span class='tag'><%= tag %></span>
            <% end %>
          </p>
          <p><%= @course.description %></p>
          <%= link_to 'Subscribe', new_course_subscription_path(course_id: @course.id), class: 'inscription-button' %>
          <p><%= @course.teachers.count %> teachers Subscribed</p>
        </div>
      </div>
      <div class='column'>
        <div class='card'>
          <h3><%= link_to "#{@course.votes.count} Votes", "/course/#{@course.id}/votes", class: '' %></h3>
          <%= form_with(url: "/votes", method: "post", remote: true) do %>
            <%= label_tag(:email, "Search for:") %>
            <%= text_field_tag(:email, '', { placeholder: 'Teacher email', id: 'search-input-email' }) %>
            <%= hidden_field_tag(:votable_id, @course.id) %>
            <%= hidden_field_tag(:votable_type, 'Course') %>
            <%= submit_tag("Vote", class: 'inscription-button') %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <% @course.subscriptions.each do |subscription| %>
        <%= render partial: './subscriptions/subscription', locals: { subscription: subscription } %>
      <% end %>
    </div>
  </div>
</secion>

app/views/dashboard/index.html.erb
<div class='board'>
  <div class='board-item'>
    <%= link_to "#{@courses_count} courses", courses_path %>
  </div>
  <div class='board-item'>
    <%= link_to "#{@teachers_count} teachers", teachers_path %>
  </div>
</div>

app/views/leaderboard/index.html.erb
<h1>Leaderboard#index</h1>
<p>Find me in app/views/leaderboard/index.html.erb</p>

app/views/subscriptions/_form.html.erb
<div id='subscription-teacher-content' class='hide'>
  <h2>Teacher</h2>
  <p><strong>Nombre: </strong> <span id='subscription-teacher-name'></span></p>
</div>

<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :teacher_email, id: 'subscription-teacher-email' %>
  <%= form.hidden_field :course_id %>
  <%= form.hidden_field :teacher_id, id: 'subscription-teacher-id' %>

  <div id='subscription-teacher-form' class='hide'>
    <p>Teacher not found. Subscribe adding the following info:</p>
    <%= label_tag(:teacher_first_name, "First name:") %>
    <%= form.text_field :teacher_first_name, id: 'subscription-teacher-first_name' %>
    <%= label_tag(:teacher_last_name, "Last name:") %>
    <%= form.text_field :teacher_last_name, id: 'subscription-teacher-last_name' %>
    <%= label_tag(:teacher_specialism, "Specialism:") %>
    <%= form.text_field :teacher_specialism, id: 'subscription-teacher-specialism' %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/subscriptions/_search_teacher.html.erb
<%= form_with(url: "/teachers", method: "get", remote: true) do %>
  <%= label_tag(:email, "Search for:") %>
  <%= text_field_tag(:email, '', { placeholder: 'Teacher email', id: 'search-input-email' }) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div class="column">
  <div class="card">
    <img src="<%= subscription.teacher.avatar %>" width="100%">
    <h3><%= teacher_full_name(subscription.teacher) %></h3>
    <p><%= subscription.teacher.email %></p>
    <p><%= subscription.teacher.specialism %></p>
    <h3><%= link_to "#{subscription.votes.count} Votes", "/subscription/#{subscription.id}/votes", class: '' %></h3>
    <%= form_with(url: "/votes", method: "post", remote: true) do %>
      <%= label_tag(:email, "Search for:") %>
      <%= text_field_tag(:email, '', { placeholder: 'Teacher email', id: 'search-input-email' }) %>
      <%= hidden_field_tag(:votable_id, subscription.id) %>
      <%= hidden_field_tag(:votable_type, 'Subscription') %>
      <%= submit_tag("Vote", class: 'inscription-button') %>
    <% end %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<section class="container">
  <div class="right-container">
    <% if @course.nil? %>
      <div class="row">
        <div class="column"><h2>All Subscriptions</h2></div>
      </div>
    <% else %>
      <div class="row">
        <%= render partial: './courses/course', locals: { course: @course } %>
      </div>
    <% end %>
    <div class="row">
      <% @subscriptions.each do |subscription| %>
        <%= render partial: 'subscription', locals: { subscription: subscription } %>
      <% end %>
    </div>
    <div class="pagination-row">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</secion>

app/views/subscriptions/new.html.erb
<section class="container">
  <div class="left-container">
    <%= render './courses/categories', selected_category: @subscription.course.category %>
  </div>
  <div class="right-container">
    <div class="row">
      <div class="column">
        <div class="card">
          <h2>Course: <%= @subscription.course.title %></h2>
          <h3><%= @subscription.course.category.name %></h3>
          <img src="<%= @subscription.course.image_src %>" width="100%">
          <p>
            <% @subscription.course.tags.each do |tag| %>
              <span class='tag'><%= tag %></span>
            <% end %>
          </p>
          <p><%= @subscription.course.description %></p>
          <p><%= @subscription.course.teachers.count %> teachers subscribed</p>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <%= render 'search_teacher', subscription: @subscription %>
        </div>
        <div class="card">
          <%= render 'form', subscription: @subscription %>
        </div>
      </div>
    </div>
  </div>
</secion>

app/views/subscriptions/show.html.erb
<h1>Subscription detail</h1>
<div class="row">
  <div class="column">
    <div class="card">
      <h2>Course</h2>
        <img src="<%= @subscription.course.image_src %>" width="100%">
        <h3><%= @subscription.course.title %></h3>
        <p><%=  %></p>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <h2>Teacher</h2>
      <img src="<%= @subscription.teacher.avatar %>" width="100%">
      <h3><%= teacher_full_name(@subscription.teacher) %></h3>
      <p><%= @subscription.teacher.email %></p>
      <p><%= @subscription.teacher.specialism %></p>
    </div>
  </div>
</div>
<div class="row">
  <div class="column">
    <div class="card">
      <h3><%= @subscription.votes.size %> votes</h3>
      <% @subscription.votes.each do |vote| %>
        <img src="<%= @subscription.teacher.avatar %>" width="100px">
        <h5><%= teacher_full_name(vote.voted_by) %></h5>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div class="column">
  <div class="card">
    <img src="<%= teacher.avatar %>" width="100%">
    <h3><%= teacher_full_name(teacher) %></h3>
    <p><%= teacher.email %></p>
    <p><%= teacher.specialism %></p>
  </div>
</div>

app/views/teachers/index.html.erb
<section class="container">
  <div class="right-container">
    <% if @course.nil? %>
      <div class="row">
        <div class="column"><h2>All Teachers</h2></div>
      </div>
    <% else %>
      <div class="row">
        <%= render partial: './courses/course', locals: { course: @course } %>
      </div>
    <% end %>
    <div class="row">
      <% @teachers.each do |teacher| %>
        <%= render partial: 'teacher', locals: { teacher: teacher } %>
      <% end %>
    </div>
    <div class="pagination-row">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</secion>

app/views/teachers/index.js.erb
<% teacher = @teachers.first %>

<% if teacher %>
    document.getElementById('subscription-teacher-id').value = '<%= teacher.id %>'
    document.getElementById('subscription-teacher-name').innerHTML = '<%= teacher_full_name(teacher) %>'
    document.getElementById('subscription-teacher-content').classList.remove('hide')
    document.getElementById('subscription-teacher-form').classList.add('hide')
    document.getElementById('subscription-teacher-email').value = ''
    document.getElementById('subscription-teacher-first_name').value = ''
    document.getElementById('subscription-teacher-last_name').value = ''
    document.getElementById('subscription-teacher-specialism').value = ''
<% else %>
    document.getElementById('subscription-teacher-id').value = ''
    document.getElementById('subscription-teacher-content').classList.add('hide')
    document.getElementById('subscription-teacher-form').classList.remove('hide')
    document.getElementById('subscription-teacher-email').value = document.getElementById('search-input-email').value
<% end %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/votes/index.html.erb
<section class="container">
  <div class="right-container">
    <div class="row">
      <div class="card">
        <h3><%= @votable.inspect %></h3>
      </div>
      <div class="card">
        <h3><%= @votes.size %> votes</h3>
      </div>
    </div>
    <div class="row">
      <% @votes.each do |vote| %>
        <%= render partial: './teachers/teacher', locals: { teacher: vote.voted_by } %>
      <% end %>
    </div>
    <div class="pagination-row">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</secion>